### ISSUE TITLE
Error: 'names' attribute [8] must be the same length as the vector [0]

### ISSUE THREAD

**Issue by gosselinm** [NCBI-Hackathons/GeneHummus#4]
When running the script for the ‘shiny’ function:

Loading (ARFLegumes.RData), since the file name in the script (shinyARFlegumes.Rdata)is not included in the available data, 

Error: 'names' attribute [8] must be the same length as the vector [0]

From line 22 

In isolating the line that gets the ‘names’, 
x=as.data.frame(my_tables[input$species])

r returns the following error:

Error in as.data.frame(my_tables[input$species]) : 
  object 'my_tables' not found

**Comment by gosselinm** [comment]
Upon re downloading all of data files, the error no longer exists. The problem was most likely from moving files around and out of the places that the r scripts think that they were.

**Comment by jdieramon** [comment]
Hi gosselinm! Actually, we have re-loaded the object and defined the right path for the shiny app. 
Thanks for bringing this up to our attention and enjoy GeneHummus!
