### ISSUE TITLE
SPP Extract Issue

### ISSUE THREAD

**Issue by laitanawe** [NCBI-Hackathons/GeneHummus#5]
I'm unable to obtain species from ARFids because it says that the request is too large.
spp = extract_spp(my_values_subset)
Error in entrez_check(response) :
 HTTP failure 414, the request is too large. For large requests, try using web history as described in the rentrez tutorial

**Comment by jdieramon** [comment]
A stable version of this package is available on CRAN and can be installed directly from there: `install.packages("geneHummus")`
It should work fine. Give it a try and let us know if you find any problem.
