### ISSUE TITLE
Info for non-model organism species

### ISSUE THREAD

**Issue by KristinaGagalova** [NCBI-Hackathons/GeneHummus#7]
Hi, 

I have a question about non-model organism species. 
I was wondering if there is a way to combine newly discovered genes from non-model species to the ones that already have an ids and are in NCBI.
I believe the tool is mainly applied to species that are re-sequenced as in the case of population genetics for example. Any chance to have it working with other species?

Thank you in advance for the future reply

Kristina

**Comment by jdieramon** [comment]
Hi Kristina, 
As the pipeline is based mainly on [RefSeq](https://www.ncbi.nlm.nih.gov/refseq/) database , your organism needs to have a [taxonomy id](https://www.ncbi.nlm.nih.gov/taxonomy) and, to best performance, it requires a reference sequence of transcripts, or/and proteins. 
Do you have any particular organism in mind ?

**Comment by KristinaGagalova** [comment]
Hi, 
Thank you for the fast reply.
My organism actually has a taxonomy id. I am working with spruce. 

The major problem is that we don't have a reference proteome/transcriptome (The annotation that i run will be the first one deposited on NCBI so far, excluding the organellar genomes).
![Screenshot from 2019-12-23 11-01-59](https://user-images.githubusercontent.com/25466163/71375745-1d865b80-2574-11ea-86b7-3097c8722f58.png)

How is the performance without a reference set of sequences?

**Comment by jdieramon** [comment]
Hi Kristina, 
I have checked the databases and , exactly right as you said, the [protein](https://www.ncbi.nlm.nih.gov/protein) database contains only entries from chloroplast and plastid. Only 74 are hosted by RefSeq. So, unfortunately it won't work at this stage. However, let us know as soon as you upload your annotation and we 'll run a demo for your sequences.

**Comment by KristinaGagalova** [comment]
Sounds good! Thank you for the help
